### ISSUE TITLE
Week5 Jwong and Sukhmer

### ISSUE THREAD

**Issue by rahkhadi** [rahkhadi/PRJ-team#8]
@shayer5 and @jwongsenec you both have to work on "Prototype: UI/UXD - Wireframes/Mock-ups" and please post it before class so professor can give feedback

**Comment by jwongsenec** [comment]
[wireframe (1).docx](https://github.com/user-attachments/files/15753656/wireframe.1.docx)

**Comment by shayer5** [comment]
Hey I added 3 extra pages to finish out the site with the homepage, account creation, as well as checkout. I also updated 2 of the previous ones done and added a few extra elements to them in this file. (this file also includes the previous wireframe doc from above so that we can keep all our pages together).
[PRJwireframesSukhman.docx](https://github.com/user-attachments/files/15756160/PRJwireframesSukhman.docx)
